# Generated by Django 3.1 on 2020-08-29 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
        model_name='customuserwithemail',
        name='id'
    ),

        migrations.AddField(
            model_name='customuserwithemail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
