# Generated by Django 3.1 on 2020-08-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0002_auto_20200829_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserWithEmail',
        ),
    ]
