# Generated by Django 3.1 on 2020-08-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0005_restaurateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurateur',
            name='test',
        ),
    ]
