# Generated by Django 3.1 on 2020-08-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('DionysosServer', '0006_remove_restaurateur_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurateur',
        ),
    ]
