# Generated by Django 3.1 on 2020-08-29 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DionysosServer', '0008_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='UserProfile',
        ),
    ]
