# Generated by Django 3.1 on 2020-08-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0010_auto_20200829_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('BR', 'Validée'), ('PA', 'Payée'), ('JR', 'Livrée'), ('AN', 'Annulée')], default='BR', max_length=2),
        ),
    ]
