# Generated by Django 3.1 on 2020-08-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0011_auto_20200829_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedFood',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DionysosServer.food')),
            ],
            bases=('DionysosServer.food',),
        ),
        migrations.AlterField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
    ]
