# Generated by Django 3.1 on 2020-08-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0012_auto_20200829_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='foods',
            new_name='ordered_foods',
        ),
    ]
