# Generated by Django 3.1 on 2020-08-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0013_auto_20200829_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
