# Generated by Django 3.1 on 2020-08-29 21:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0015_auto_20200829_2301'),
    ]

    operations = [
        migrations.DeleteModel('orderedfood'),
        migrations.CreateModel('orderedfood', fields=[
            ('id',
            models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False))
        ]),
        migrations.AddField(
            model_name='orderedfood',
            name='food',
            field=models.ForeignKey(default='1411eb33-5dc9-4c9f-b840-16e84e96c7ce', on_delete=django.db.models.deletion.CASCADE, to='DionysosServer.food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='paid_price',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
