# Generated by Django 3.1 on 2020-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0017_auto_20200829_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('VA', 'Validée'), ('PA', 'Payée'), ('JR', 'Livrée'), ('AN', 'Annulée')], default='VA', max_length=2),
        ),
    ]
