# Generated by Django 3.1 on 2020-08-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0020_auto_20200829_2323'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='order',
        #    name='ordered_foods',
        #),
    ]
