# Generated by Django 3.1 on 2020-08-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0022_remove_order_ordered_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
    ]
