# Generated by Django 3.1 on 2020-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0024_auto_20200830_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
    ]
