# Generated by Django 3.1 on 2020-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0025_auto_20200830_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
    ]
