# Generated by Django 3.1.1 on 2020-09-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0028_auto_20200904_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
    ]
