# Generated by Django 3.1.1 on 2020-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0029_auto_20200904_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profilePicHash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
    ]
