# Generated by Django 3.1.1 on 2020-10-05 15:50

import DionysosServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DionysosServer', '0036_auto_20201004_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_seller_id',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[DionysosServer.models.UserProfile.validate]),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_foods',
            field=models.ManyToManyField(to='DionysosServer.OrderedFood'),
        ),
    ]
